name: Build and Test Docker App

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t django-app .

      - name: Run container
        run: docker run -d -p 8000:8000 django-app

      - name: Wait for app
        run: sleep 10

      - name: Test with curl
        run: curl http://localhost:8000
